### ISSUE TITLE
Reasoning behind inv in FlowDistr

### ISSUE THREAD

**Issue by akashsengupta1997** [pimdh/relie#1]
Hi, thanks for compiling this very well-organised repo, it has been a joy to work with!

I have a question about the following lines in the FlowDistr class definition in so3_multimodal_flow.py :
```
 def transforms(self):
        transforms = [
            self.flow().inv,
            intermediate_transform,
            SO3ExpCompactTransform(algebra_support_radius),
        ]
        return transforms
```
Why is the flow transformation specified as the inverse of the flow transformation defined using the Flow class? I understand that theoretically this makes no difference since the flow transformation is a bijective mapping; but practically it seems like the flow training (i.e. log_prob evaluation) is much faster by specifying the transformation as the inverse. Is it something along the lines of the inverse transform being pre-computed / not being repeatedly computed during log_prob evaluation?

**Comment by pimdh** [comment]
Hi, 
Thanks for your question. I'm not quite sure, to be honest. I suspect that both the forward and the backward would work equally well. For the affine coupling layers, flowing forward and backward should also be practically interchangeable (different from e.g. autiregressive flows). I haven't tested, but I think the code also works if you remove the `.inv`. It's a while ago since I wrote this, so I may be forgetting a subtlety here.
Pim

**Comment by akashsengupta1997** [comment]
Thanks for your reply Pim! The code does indeed work with ```.inv``` removed; however it is approximately 1.5-2x slower on both CPU and GPU for me. I guess you had figured this a while ago and that's why you put the ```.inv``` there :)
