### ISSUE TITLE
N(0, scale), exp, multiply \mu OR N(\mu, scale), exp

### ISSUE THREAD

**Issue by yd-yin** [pimdh/relie#5]
Hi, thanks for your really amazing work!

I wonder when reparametrization is not a must, e.g., MLE, the predicted $\mu$ should be used after exp via `SO3MultiplyTransform` or before exp as the mean of the Euclidean Gaussian? I.e., like the title, the procedure should be N(0, scale) $\rightarrow$ exp $\rightarrow$ multiply $\mu$ or N(\mu, scale) $\rightarrow$ exp?

Note that in readme, it is the former case, while in experiment 
https://github.com/pimdh/relie/blob/master/relie/experiments/so3_conditional_mle.py#L90, it is the latter case.

Is there any preference?

Thanks in advance!

**Comment by pimdh** [comment]
Translating by the mean after exp would have my preference. In that case you get that the distribution "looks the same", just shifted. When doing exp(N(log mu, scale)), the resulting distribution is different depending on the mean, due to the deformation of exp. For example, I wouldn't be even sure if in that case the geometric mean (the point with smallest squared Riemannian distance to samples) would even be at mu.

**Comment by yd-yin** [comment]
I got it. Thanks for the really quick response!
